sudo: required

language: go 

services:
  - docker

go:
  - 1.5.1

script:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker -v
  - make docker
  - tail -n 1000 /tmp/buildlog.txt

env:
  global:
  - secure: PVvU1/VDI6Q3RoA2UFJfWM8NmI40TrU6wujlPQvXmZlFIEjmPVpZeEtr1gkyWGgLHSeRUmzD8A1/qSk17zphb5lnlrfiEUyNguCGHPjtvg/aS7YdVOBJCfi7tg9Qd2jDWzn5MXYxoaCCeHJRu5ORmg4nlnbCOkBhfufxSZDX+Go3lNL3VFeqVPTO/sKPe6D1XjaeVZNnBmASYAgzqzxf1yzJ70h84r9wl093bWyqsdO9ojAF4WWO5DM4ojJnBN5F35YaAd4kR+Nw2OfwD37hj7c33e01rBD8vi8ch6sSMC3fTg5TONB1OK8zQWYh8rcMMLCSF79XxZ6iPTsPY0wunnS6lLe16ywW3OUR+7U3HreO6ZpCp/b+/VzrjXBpKob8g87TWbD+Iki+IzSJVh8I6bpZU8BazHuzOI90MTrlwMX7RTmOxrrwmv+jYe2g0FKNYk/UXL3nG7v3Pf/6mrZF4HiR+ShkHwevrq4X+bcIhSnzfVO2kL0BdCjJ8iXBpRcMg+4E3pZS811/XLDDA/b34bErCA+cgyJRpOqVxJ/ONqhrIDK/2oZX6lV7tuEhe0VDFDMfH9pIOgd/1lQuedKZKQfmDJX2v8LaN9hQE8XyM/EI9+3gkK7SFIbVMLPWKLnA1MniP4uFeFXyO18PEO2IuLcME3XWMRzEn+ee1Ip2OSM=
  - secure: m1IHbLCExBfplFwIFKiaBgSjG2DoXXSdLn2azUPXVvCVq2Uo/8Cf0l1mocJWuqAO/RE/YmIocIK9iTgtuPjXe6znTjeG0yOBr/pL+hYXPDATbQJpgXKdb1oWqNEagfFPTf9GVa/wgdH3ai6YnZtzdRC+tMqWqflvRmKxLmhioRlwHhm1i8tw1hMLlCL/TSM5FqRblwEzpH/2dcsNTtFE3EO8zA6/F58RoHVHdSg21inpPPMmGsjCkypFG7c5a3tKV15mjcYVjkXs0aRBoabwgzA4vPv+0KzufYiv6c5Ubmrfa53SQqGkdaieFc2taA5/SUqzbPkH7zEs4OMP1m/NQr55KIp8SwQc5n9qv1YYJDY/XPlZVammS5jrBiz8oC6n2XEHFn8eTwCHgZU9JBBXYAW+vR2ZN4/Ke3r6fVPGFGokZdCmB5isWLIatOuBt419fRPpKvYh5Dv/ZUgl7LHd3CZLo43UneQS1XNrBPjEPJE/7UvauTGR7dQe0R9/uiMS1cn5qrVnP4Lo+j75GEVzP3/G5NmVsD/0UgBtJyVNYt2L8T+a3nS4MOeptN3a1FcgwT0Oh1ZblmwPuH28QDemRl3/Hj/HK8wwKxV+luFY6bhvv8tx10JfGIJSKMHcPRGtyRwXoBdvwNAKFHsjiUH5wdaMGdayUteqPMuK1RHVyCY=
  - secure: ItItnb4R4h9jD+zf0DBXbSpxVurWvu/sB8rcwE3A6W4d2nn1qJhbfwaPZeROVa57ISsYJ3PBdLvs66iVsh8xuVfYFFlExaON2GOvDiuwzY+L7luOAa3phPOUc7FnFzmhmV6VpsDwKGvvrnkOG6tlXutxCdfDmTm8B6T3H7DbVQbHObErJDXxO631olM1UOK3SNBq4QSGQvWIAvDKR9tKywxopdeKwRYll8Sf6yIVoTjG8pLx3tW7AizbDvohEUKjhWvJvrsHjWBwn/sXSrplzjZ6l07uTyDnRdyL5roeY1TTe4+3nLnK3N0jFJiULShs9hvBMcJmqmYh7+hVw0zuPXyZVpZ+Hh6D5IYx8aGrBBTLEr/tFJerdTxcqBp4hR9WhidnYHmGb/bjvPrvk1hhtU8fcaViww8VqAHRtNrEcMgjQqEYnc4fZ2BH5wUoLBpQgKvLHtWpClVmZCzxLcEg1a1sBt5CUUxk4uqDUTakKBE+yxFBD7hSG4M4JMT1mGR/H7PuDqFDVZnF1AAOgEhpm/KkoAyGriznbyhj8bHR+eG2WnoqmjeUSW/dHRwfqfaiB8DlwBmSqVVWrEgdRiGeXarD/+ld8I5SxCLyT53SNL2KGcu/Di3eSEygR1UlteP6Am7KczcrODzDturIHU53qs6SWRt5S+4NZ2P0/IcoqQU=
